name: Running Docker
description: Resulting docker container contains all necessary semgrep executions
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ip }}
    - ${{ inputs.port }}