name: Semgrep
on:
  push:
    paths:
      - '<REPLACE_PATH>/**'
jobs:
  semgrep:
    name: Executing semgrep rules
    runs-on: ubuntu-latest
    steps:
      # Fetch project source code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Executing semgrep rules
        uses: ./<REPLACE_PATH>/semgrep/.
        with:
          ip: ${{ secrets.IP }}
          port: ${{ secrets.PORT }}